# Generated by Django 4.1.2 on 2022-11-08 06:17

import apps.discount.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contacts', models.CharField(max_length=500)),
                ('social_link', models.TextField()),
                ('operating_mode', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to=apps.discount.models.upload_image)),
            ],
        ),
        migrations.CreateModel(
            name='DiscountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.ManyToManyField(blank=True, null=True, to='discount.discount')),
            ],
        ),
    ]
