# Generated by Django 4.1.2 on 2023-01-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discount',
            old_name='operating_mode',
            new_name='cashback',
        ),
        migrations.RenameField(
            model_name='discount',
            old_name='contacts',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='discount_type_id',
        ),
        migrations.RemoveField(
            model_name='discount',
            name='social_link',
        ),
        migrations.AddField(
            model_name='discount',
            name='discount_type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='end_of_action',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='percentage',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='price_before',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='discount',
            name='promotion_condition',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='referral_link',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='start_of_action',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
