# Generated by Django 4.1.2 on 2023-01-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_rename_operating_mode_discount_cashback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='cashback',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='discount',
            name='percentage',
            field=models.IntegerField(default=0),
        ),
    ]
