# Generated by Django 4.1.2 on 2023-01-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0004_alter_discount_cashback_alter_discount_percentage'),
        ('cart', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='discount',
            field=models.ManyToManyField(to='discount.discount'),
        ),
    ]
