# Generated by Django 4.1.2 on 2022-10-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partner',
            name='activity_type',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='myuser_ptr',
        ),
    ]
