# Generated by Django 4.1.2 on 2022-10-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_remove_partner_activity_type_and_more'),
        ('discount', '0003_alter_discount_partner_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partner',
        ),
    ]
