# Generated by Django 4.1.2 on 2023-01-31 16:15

import apps.users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=255, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("Клиент", "Клиент"),
                            ("Партнер", "Партнер"),
                            ("Администратор", "Администратор"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PartnerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand_name", models.CharField(max_length=255)),
                ("organization_form", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("inn", models.CharField(max_length=255)),
                ("isVip", models.BooleanField(default=False)),
                (
                    "transaction_quantity",
                    models.IntegerField(blank=True, default=0, null=True),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        null=True,
                        upload_to=apps.users.models.upload_logo,
                    ),
                ),
                (
                    "banner",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        null=True,
                        upload_to=apps.users.models.upload_banner,
                    ),
                ),
                (
                    "phone_number2",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number3",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "phone_number4",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("whatsapp", models.CharField(blank=True, max_length=255, null=True)),
                ("youtube", models.CharField(blank=True, max_length=255, null=True)),
                ("telegram", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                ("schedule", models.CharField(max_length=255)),
                ("start", models.CharField(max_length=255)),
                ("end", models.CharField(max_length=255)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ClientProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("surname", models.CharField(max_length=255)),
                ("date_of_birth", models.DateField()),
                (
                    "discount_card_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="user_default.png",
                        null=True,
                        upload_to="user_image",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
