# Generated by Django 4.1.2 on 2022-10-15 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activity_type', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('brand_name', models.CharField(max_length=255)),
                ('organization_form', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('inn', models.CharField(max_length=255)),
                ('isVip', models.BooleanField(default=False)),
                ('transaction_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('activity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='activity_type.activitytype')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.myuser',),
        ),
        migrations.AddField(
            model_name='customuser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='following', to='users.partner'),
        ),
    ]
