# Generated by Django 4.1.2 on 2022-11-09 14:03

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(default='default.png', upload_to=apps.users.models.upload_logo),
        ),
    ]
