# Generated by Django 4.1.2 on 2022-12-14 09:11

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_partner_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='banner',
            field=models.ImageField(default='default.png', upload_to=apps.users.models.upload_banner),
        ),
    ]
