# Generated by Django 4.1.2 on 2023-01-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_partner_end_partner_facebook_partner_phone1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersocialmedia',
            name='partner',
        ),
        migrations.RemoveField(
            model_name='workingmode',
            name='partner',
        ),
        migrations.DeleteModel(
            name='PartnerPhoneNumber',
        ),
        migrations.DeleteModel(
            name='PartnerSocialMedia',
        ),
        migrations.DeleteModel(
            name='WorkingMode',
        ),
    ]
