# Generated by Django 4.1.2 on 2023-01-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_partnersocialmedia_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
