# Generated by Django 4.1.2 on 2023-01-03 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_partner_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('myuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('date_of_birth', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.myuser',),
        ),
        migrations.RemoveField(
            model_name='user',
            name='contract_offer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='discount_card_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='user_default.png', upload_to='user_image'),
        ),
    ]
