# Generated by Django 4.1.2 on 2023-01-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_admin_remove_user_contract_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='discount_card_number',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
